inherit_from: .rubocop_todo.yml

require:
  - rubocop-performance
  - rubocop-rails
Layout/SpaceInsideArrayLiteralBrackets:
  Enabled: false
Rails/CreateTableWithTimestamps:
  Enabled: false
Style/AsciiComments:
  Enabled: false
Style/EmptyMethod:
  Enabled: false
Style/GlobalStdStream:
  Enabled: false
Style/ClassAndModuleChildren:
  Enabled: false
Style/GuardClause:
  Enabled: false
Naming/MethodParameterName:
  Enabled: false
Rails/FilePath:
  EnforcedStyle: slashes
Rails/HttpStatus:
  EnforcedStyle: numeric
Style/Documentation:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Style/StringLiterals:
  Enabled: false
Metrics/AbcSize:
  Max: 23
Metrics/BlockLength:
  Max: 298
Metrics/MethodLength:
  Max: 25
Layout/LineLength:
  Max: 258
